// <auto-generated />
using System;
using InTechNet.DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace InTechNet.DataAccessLayer.Migrations
{
    [DbContext(typeof(InTechNetContext))]
    [Migration("20200314152709_migration_intechnet")]
    partial class migration_intechnet
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("InTechNet.DataAccessLayer.Entity.Attendee", b =>
                {
                    b.Property<int>("IdAttendee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("HubIdHub")
                        .HasColumnType("integer");

                    b.Property<int>("IdHub")
                        .HasColumnType("integer");

                    b.Property<int>("IdPupil")
                        .HasColumnType("integer");

                    b.Property<int?>("PupilIdPupil")
                        .HasColumnType("integer");

                    b.HasKey("IdAttendee");

                    b.HasIndex("HubIdHub");

                    b.HasIndex("PupilIdPupil");

                    b.ToTable("attendee","public");
                });

            modelBuilder.Entity("InTechNet.DataAccessLayer.Entity.Hub", b =>
                {
                    b.Property<int>("IdHub")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("HubCreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("HubLink")
                        .HasColumnType("text");

                    b.Property<string>("HubName")
                        .HasColumnType("text");

                    b.Property<int?>("ModeratorIdModerator")
                        .HasColumnType("integer");

                    b.HasKey("IdHub");

                    b.HasIndex("HubName");

                    b.HasIndex("ModeratorIdModerator");

                    b.ToTable("hub","public");

                    b.HasData(
                        new
                        {
                            IdHub = 1,
                            HubCreationDate = new DateTime(2020, 3, 14, 16, 27, 9, 357, DateTimeKind.Local).AddTicks(3960),
                            HubLink = "hublink1",
                            HubName = "supername"
                        });
                });

            modelBuilder.Entity("InTechNet.DataAccessLayer.Entity.Moderator", b =>
                {
                    b.Property<int>("IdModerator")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ModeratorEmail")
                        .HasColumnType("text");

                    b.Property<string>("ModeratorNickname")
                        .HasColumnType("text");

                    b.Property<string>("ModeratorPassword")
                        .HasColumnType("text");

                    b.Property<string>("ModeratorSalt")
                        .HasColumnType("text");

                    b.HasKey("IdModerator");

                    b.HasIndex("ModeratorNickname");

                    b.ToTable("moderator","public");

                    b.HasData(
                        new
                        {
                            IdModerator = 1,
                            ModeratorEmail = "test@test.com",
                            ModeratorNickname = "modeNick",
                            ModeratorPassword = "CC3827BF052E6B257CE6FBE896077A132448552CA6746CD538A11039950636ABD7440927318E5D9EBBD151C6A93364B8F5AD761A871403227395F4D99D01E34A",
                            ModeratorSalt = "lesaltcestbien"
                        });
                });

            modelBuilder.Entity("InTechNet.DataAccessLayer.Entity.Pupil", b =>
                {
                    b.Property<int>("IdPupil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("PupilEmail")
                        .HasColumnType("text");

                    b.Property<string>("PupilNickname")
                        .HasColumnType("text");

                    b.Property<string>("PupilPassword")
                        .HasColumnType("text");

                    b.Property<string>("PupilSalt")
                        .HasColumnType("text");

                    b.HasKey("IdPupil");

                    b.HasIndex("PupilNickname");

                    b.ToTable("pupil","public");

                    b.HasData(
                        new
                        {
                            IdPupil = 1,
                            PupilEmail = "pupil@pupil.com",
                            PupilNickname = "pupilNick",
                            PupilPassword = "4230B63D16DCEF8861AA9BE6F93B46F2E2ED20EC6C3E7E6001CDEC44DE1186BA015D98F19D3D5C43D38F84CBD00FDC977058066791A2AF7ACFE8863F92C71F8B",
                            PupilSalt = "leselcestdrole"
                        });
                });

            modelBuilder.Entity("InTechNet.DataAccessLayer.Entity.Attendee", b =>
                {
                    b.HasOne("InTechNet.DataAccessLayer.Entity.Hub", "Hub")
                        .WithMany("Attendees")
                        .HasForeignKey("HubIdHub");

                    b.HasOne("InTechNet.DataAccessLayer.Entity.Pupil", "Pupil")
                        .WithMany("Attendees")
                        .HasForeignKey("PupilIdPupil");
                });

            modelBuilder.Entity("InTechNet.DataAccessLayer.Entity.Hub", b =>
                {
                    b.HasOne("InTechNet.DataAccessLayer.Entity.Moderator", "Moderator")
                        .WithMany("Hubs")
                        .HasForeignKey("ModeratorIdModerator");
                });
#pragma warning restore 612, 618
        }
    }
}
