// <auto-generated />
using System;
using InTechNet.DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace InTechNet.DataAccessLayer.Migrations
{
    [DbContext(typeof(InTechNetContext))]
    [Migration("20200315003741_CleanDataIntablesMigration")]
    partial class CleanDataIntablesMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("InTechNet.DataAccessLayer.Entity.Attendee", b =>
                {
                    b.Property<int>("IdAttendee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("HubIdHub")
                        .HasColumnType("integer");

                    b.Property<int>("IdHub")
                        .HasColumnType("integer");

                    b.Property<int>("IdPupil")
                        .HasColumnType("integer");

                    b.Property<int?>("PupilIdPupil")
                        .HasColumnType("integer");

                    b.HasKey("IdAttendee");

                    b.HasIndex("HubIdHub");

                    b.HasIndex("PupilIdPupil");

                    b.ToTable("attendee","public");
                });

            modelBuilder.Entity("InTechNet.DataAccessLayer.Entity.Hub", b =>
                {
                    b.Property<int>("IdHub")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("HubCreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("HubLink")
                        .HasColumnType("text");

                    b.Property<string>("HubName")
                        .HasColumnType("text");

                    b.Property<int?>("ModeratorIdModerator")
                        .HasColumnType("integer");

                    b.HasKey("IdHub");

                    b.HasIndex("HubName");

                    b.HasIndex("ModeratorIdModerator");

                    b.ToTable("hub","public");

                    b.HasData(
                        new
                        {
                            IdHub = 1,
                            HubCreationDate = new DateTime(2020, 3, 15, 1, 37, 41, 171, DateTimeKind.Local).AddTicks(5448),
                            HubLink = "hub-link",
                            HubName = "hub-name"
                        });
                });

            modelBuilder.Entity("InTechNet.DataAccessLayer.Entity.Moderator", b =>
                {
                    b.Property<int>("IdModerator")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ModeratorEmail")
                        .HasColumnType("text");

                    b.Property<string>("ModeratorNickname")
                        .HasColumnType("text");

                    b.Property<string>("ModeratorPassword")
                        .HasColumnType("text");

                    b.Property<string>("ModeratorSalt")
                        .HasColumnType("text");

                    b.HasKey("IdModerator");

                    b.HasIndex("ModeratorNickname");

                    b.ToTable("moderator","public");

                    b.HasData(
                        new
                        {
                            IdModerator = 1,
                            ModeratorEmail = "moderator@intechnet.io",
                            ModeratorNickname = "moderator",
                            ModeratorPassword = "720E39C10B81B3652B149FA74B3757AD1453F10FD4445F2A1AB4196BF2D23CE5D64A8DCD6DE157194853F35CC160F8A851155261B82B271BB81AD0B700AF9992",
                            ModeratorSalt = "moderator-salt"
                        });
                });

            modelBuilder.Entity("InTechNet.DataAccessLayer.Entity.Pupil", b =>
                {
                    b.Property<int>("IdPupil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("PupilEmail")
                        .HasColumnType("text");

                    b.Property<string>("PupilNickname")
                        .HasColumnType("text");

                    b.Property<string>("PupilPassword")
                        .HasColumnType("text");

                    b.Property<string>("PupilSalt")
                        .HasColumnType("text");

                    b.HasKey("IdPupil");

                    b.HasIndex("PupilNickname");

                    b.ToTable("pupil","public");

                    b.HasData(
                        new
                        {
                            IdPupil = 1,
                            PupilEmail = "pupil@intechnet.io",
                            PupilNickname = "pupil",
                            PupilPassword = "CF28AF1039C0348CE7715232444454F47E085D6859913BFE531008D1BEF4992D27D7A3301E9CC70004F0F42513676FC01B941C848160351D389BBC3A264DC0E2",
                            PupilSalt = "pupil-salt"
                        });
                });

            modelBuilder.Entity("InTechNet.DataAccessLayer.Entity.Attendee", b =>
                {
                    b.HasOne("InTechNet.DataAccessLayer.Entity.Hub", "Hub")
                        .WithMany("Attendees")
                        .HasForeignKey("HubIdHub");

                    b.HasOne("InTechNet.DataAccessLayer.Entity.Pupil", "Pupil")
                        .WithMany("Attendees")
                        .HasForeignKey("PupilIdPupil");
                });

            modelBuilder.Entity("InTechNet.DataAccessLayer.Entity.Hub", b =>
                {
                    b.HasOne("InTechNet.DataAccessLayer.Entity.Moderator", "Moderator")
                        .WithMany("Hubs")
                        .HasForeignKey("ModeratorIdModerator");
                });
#pragma warning restore 612, 618
        }
    }
}
